---
knit: "bookdown::render_book"
---

# Publications during enrolment {-}

This thesis by publication is built around four articles which are at different stages of publication.

1. Chapter \ref{ch:paper2} has been submitted to the *International Journal of Forecasting*  for possible publication.

    Talagala, T. S., Hyndman, Rob. J., & Athanasopoulos, G. (2018). Meta-learning how to forecast time series. Working Paper 6/18. Department of Econometrics & Business Statistics, Monash University.
  

2. Chapter \ref{ch:paper3} is ready for submission to *Computational Statistics & Data Analysis*.

     Talagala, T. S., Hyndman, R. J., & Athanasopoulos, G. (2019). Peeking inside FFORMS: Feature-based forecast model selection. Computational Statistics & Data Analysis [ready for submission].

    
3. Chapter \ref{ch:paper4}  has been accepted for publication in the *International Journal of Forecasting* and is currently in press.

    Montero-Manso, P., Athanasopoulos, G., Hyndman, R. J., Talagala, T. S. (2019) FFORMA: Feature-based forecast model averaging. International Journal of Forecasting [to appear]
    
  
4. Chapter \ref{ch:paper5} has been submitted to the *International Journal of Forecasting*  for possible publication. 

    Talagala, T. S., Feng, L.,  & Kang, Y. (2019). FFORMPP: Feature-based forecast model performance prediction. International Journal of Forecasting [under review].

The contributions in Chapters \ref{ch:paper2} - \ref{ch:paper5} of this thesis were presented at the following events:
  
- 37th International Symposium on Forecasting 2017, Cairns, Australia.
- Young Statisticians Conference 2017, Tweed Heads, NSW, Australia. \newline A Statistical Society of Australia travel award grant was received to attend the conference.
- Young Stats Showcase hosted by the Statistical Society of Australia, Victorian Branch, Australia, in September 2017.
- 38th International Symposium on Forecasting 2018,  Boulder, Colorado, USA, in June 2018 \newline
An International Institute of Forecasters travel award grant was received to attend the conference.
- 2018 Joint Statistical Meetings (JSM2018), Vancouver, British Columbia, Canada, in August 2018
- useR! 2018, Brisbane, Australia, in July 2018 
- Invited talk, Central University of Finance and Economics, Beijing, China, in March 2019
- 39th International Symposium on Forecasting, Thessaloniki, Greece, in June 2019  \newline An International Institute of Forecasters travel award grant was received to attend the conference.
- useR! 2019, Toulouse, France, in July 2019
 

